<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title><?php print($this->config->appTitle)?></title>

	<meta name="description" content="<?php print($this->config->appTitle)?>">
	<meta name="author" content="<?php print($this->config->appAutor)?>">
	<meta name="robots" content="noindex, nofollow">

	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

	<link rel="shortcut icon" href="<?php print($this->url->get("img/favicon.png"))?>">

	<!-- Icons -->
	<!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
	<!-- END Icons -->

	<!-- Stylesheets -->
	<!-- Bootstrap is included in its original form, unaltered -->
    <?php print($this->tag->stylesheetLink("css/bootstrap.min.css"))?>

	<!-- Related styles of various icon packs and plugins -->
    <?php print($this->tag->stylesheetLink("css/plugins.css"))?>

	<!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
    <?php print($this->tag->stylesheetLink("css/main.css"))?>

	<!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
    <?php print($this->tag->stylesheetLink("css/themes.css"))?>

    <!-- tema personalizado para bc -->
    <?php print($this->tag->stylesheetLink("css/bcentral-custom.css"))?>
	<!-- END Stylesheets -->

	<?php
		if(isset($addCss)){
			foreach($addCss as $link){
				print($this->tag->stylesheetLink($link));
			}
		}
	?>
	
	<!-- Modernizr (browser feature detection library) & Respond.js (enables responsive CSS code on browsers that don't support it, eg IE8) -->
	<?php print($this->tag->javascriptInclude("js/vendor/modernizr-respond.min.js"))?>

</head>
<body>
		<div id="page-container" class="style-alt">
	        <!-- Main Container -->
	        <div id="main-container">
	        	<?php if(!isset($disableUserNav)) { ?>
	            <header class="navbar navbar-default theme-banco-central ">
	                <!-- Navbar Header -->
		            <div class="navbar-header">
		                <!-- Horizontal Menu Toggle + Alternative Sidebar Toggle Button, Visible only in small screens (< 768px) -->
		                <ul class="nav navbar-nav-custom pull-right visible-xs">
		                    <li>
		                        <a href="javascript:void(0)" data-toggle="collapse" data-target="#horizontal-menu-collapse">Menu</a>
		                    </li>
		                </ul>
		                <!-- END Horizontal Menu Toggle + Alternative Sidebar Toggle Button -->

		            </div>
		            <!-- END Navbar Header -->
		            
		            <div id="horizontal-menu-collapse" class="collapse navbar-collapse">

			            <!-- Alternative Sidebar Toggle Button, Visible only in large screens (> 767px) -->
			            <ul class="nav navbar-nav-custom pull-right hidden-xs">
							<li class="dropdown">
			                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
			                        <i class="gi gi-user"></i><strong> <?php print($this->auth->getName())?></strong> <i class="fa fa-angle-down"></i>
			                    </a>
			                    <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
			                        <li class="dropdown-header text-center">Opciones</li>
			                        <li>
			                            <a href="<?php print($this->url->get(""))?>logout">
			                                <i class="fa fa-ban fa-fw pull-right"></i>
			                                Desconectarse
			                            </a>
			                        </li>

			                    </ul>
			                </li>
			            </ul>
		            </div>
		            
	            </header>
	            <?php } ?>
	            <!-- END Header -->

	            <!-- Page Content -->
	            <div id="page-content" class="clearfix">
	                <!-- Dashboard Header -->
					<!-- For an image header add the class 'content-header-media' and an image as in the following example -->
					<div class="content-header content-header-media ">
					    <div class="header-section header-section-bc">
					        <div class="row">
					            <!-- Main Title (hidden on small devices for the statistics to fit) -->
					            <div class="col-md-2 col-lg-2 col-xs-2" style="text-align: center;">
					            	<a href="<?php print($this->url->get(""))?>">
					           			<img  src="<?php print($this->url->get("img/logo-bcentral-100.png"))?>" height="100" >
					           		</a>
					            </div>
					            <div class="col-md-10 col-lg-10 col-xs-10 ">
					            	<?php if(!isset($disableUserNav)) { ?>
					                <h1 class="titulo-bc">Bienvenido al <strong><?php print($this->config->appName)?></strong><br><small></small></h1>
					                <?php } ?>
					            </div>
					            <!-- END Main Title -->

					            <!-- Top Stats -->

					            <!-- END Top Stats -->
					        </div>
					    </div>
					    <!-- For best results use an image with a resolution of 2560x248 pixels (You can also use a blurred image with ratio 10:1 - eg: 1000x100 pixels - it will adjust and look great!) -->
					    <img src="<?php print($this->url->get("img/background-encabezado3.png"))?>" alt="header image" class="" style="width: 100%;opacity: 0.9;">
					</div>
					<!-- END Dashboard Header -->

				    <?php if(isset($pcView) && $pcView!=null) 
							echo $this->view->render($pcView,array('pcData'=>$pcData));
					?>


				</div>


 				<!-- Footer -->
	            <footer class="clearfix">
		            	
		                <div class="pull-right hidden-xs" >
		                	<a class="bc-text" href="http://www.bcentral.cl" >Banco Central de Chile</a>
		            	</div>
			            <div class="pull-left hidden-xs">
			                2016 &copy; <a class="bc-text" href="" target="_blank"><?php print($this->config->appName)?></a>
			            </div>
			            <div class="center-footer ">Mesa de Servicios: <i class="gi gi-earphone"></i> +56 2 2670-2337 </div>
	            </footer>
	            <!-- END Footer -->
			</div>
		</div>


	<!-- Remember to include excanvas for IE8 chart support -->
	<!--[if IE 8]><?php print($this->tag->javascriptInclude("js/helpers/excanvas.min.js"))?><![endif]-->

	<!-- jQuery, Bootstrap.js, jQuery plugins and Custom JS code -->
	<?php print($this->tag->javascriptInclude("js/vendor/jquery-1.11.3.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/vendor/bootstrap.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/plugins.js"))?>
	<?php print($this->tag->javascriptInclude("js/mifaces.js"))?>
	<?php print($this->tag->javascriptInclude("js/app.js"))?>

	<script>
		$("#likeimg").on('click', function() {
			$(this).attr("src","<?php print($this->url->get("img/like-1.png"))?>");
			$("#dislikeimg").attr("src","<?php print($this->url->get("img/like-22.png"))?>");
		});
		$("#dislikeimg").on('click', function() {
			$(this).attr("src","<?php print($this->url->get("img/like-2.png"))?>");
			$("#likeimg").attr("src","<?php print($this->url->get("img/like-11.png"))?>");
		});
	</script>
	<script>
		$("[id^=verTicket]").click(function(){
			$("#idTicket").val($(this).data('id'));
			$("#verTicketForm").submit();
		});
	</script>

	<?php
	if(isset($jsScript) && $jsScript!=null){
	?>
	<script>
	<?php print($jsScript)?>
	</script>
	<?php
		}
	?>		
	<?php
		if(isset($addJs) && $addJs!=null){
			foreach($addJs as $link){
	?>
	<?php print($this->tag->javascriptInclude($link))?>
	<?php
			}
		}
	?>
	<?php
	if(isset($jsPosScrt) && $jsPosScrt!=null){
	?>
	<script>
	<?php print($jsPosScrt)?>
	</script>
	<?php
		}
	?>	
</body>
</html>